import type { Request } from "express";
import { prisma } from "../lib/prisma.js";

export const AUDIT_ACTIONS = {
  USER_LOGIN: "USER_LOGIN",
  OWNER_LOGIN: "OWNER_LOGIN",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  WEBSITE_ENTERED: "WEBSITE_ENTERED",
  USER_VIEWED_COURTS: "USER_VIEWED_COURTS",
  USER_VIEWED_COURT_DETAILS: "USER_VIEWED_COURT_DETAILS",
  USER_STARTED_BOOKING: "USER_STARTED_BOOKING",
  BOOKING_HOLD_CREATED: "BOOKING_HOLD_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  USER_CANCELLED_BOOKING: "USER_CANCELLED_BOOKING",
  PAYMENT_ORDER_CREATED: "PAYMENT_ORDER_CREATED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_INITIATED: "REFUND_INITIATED",
  REFUND_CALCULATED: "REFUND_CALCULATED",
  OWNER_REFUND_PENDING: "OWNER_REFUND_PENDING",
  OWNER_CREATED_COURT: "OWNER_CREATED_COURT",
  OWNER_UPDATED_COURT: "OWNER_UPDATED_COURT",
  OWNER_ADDED_COURT_MOBILE: "OWNER_ADDED_COURT_MOBILE",
  OWNER_UPDATED_COURT_MOBILE: "OWNER_UPDATED_COURT_MOBILE",
  OWNER_UPDATED_CANCELLATION_CHARGE: "OWNER_UPDATED_CANCELLATION_CHARGE",
  OWNER_DELETED_COURT: "OWNER_DELETED_COURT",
  OWNER_UPLOADED_COURT_IMAGE: "OWNER_UPLOADED_COURT_IMAGE",
  OWNER_CHANGED_COURT_STATUS: "OWNER_CHANGED_COURT_STATUS",
  OWNER_VIEWED_BOOKINGS: "OWNER_VIEWED_BOOKINGS",
  OWNER_CHECKED_IN_USER: "OWNER_CHECKED_IN_USER",
  OWNER_UPDATED_PAYMENT_PROFILE: "OWNER_UPDATED_PAYMENT_PROFILE",
  OWNER_VERIFIED_DIRECT_PAYMENT: "OWNER_VERIFIED_DIRECT_PAYMENT",
  OWNER_REJECTED_DIRECT_PAYMENT: "OWNER_REJECTED_DIRECT_PAYMENT",
  OWNER_ADDED_COURT_UPI_DETAILS: "OWNER_ADDED_COURT_UPI_DETAILS",
  OWNER_UPDATED_COURT_UPI_DETAILS: "OWNER_UPDATED_COURT_UPI_DETAILS",
  OWNER_UPDATED_COURT_UPI_QR: "OWNER_UPDATED_COURT_UPI_QR",
  USER_SUBMITTED_UPI_PAYMENT: "USER_SUBMITTED_UPI_PAYMENT",
  ADMIN_APPROVED_COURT: "ADMIN_APPROVED_COURT",
  ADMIN_REJECTED_COURT: "ADMIN_REJECTED_COURT",
  ADMIN_DELETED_USER: "ADMIN_DELETED_USER",
  ADMIN_DELETED_OWNER: "ADMIN_DELETED_OWNER",
  ADMIN_CREATED_USER: "ADMIN_CREATED_USER",
  ADMIN_CREATED_OWNER: "ADMIN_CREATED_OWNER",
  ADMIN_CREATED_ADMIN: "ADMIN_CREATED_ADMIN",
  ADMIN_DELETE_USER: "ADMIN_DELETE_USER",
  ADMIN_DELETE_OWNER: "ADMIN_DELETE_OWNER",
  ADMIN_DELETE_ADMIN: "ADMIN_DELETE_ADMIN",
  ADMIN_DELETED_ADMIN: "ADMIN_DELETED_ADMIN",
  ADMIN_LIMIT_BLOCKED: "ADMIN_LIMIT_BLOCKED",
  PUBLIC_ADMIN_SIGNUP_BLOCKED: "PUBLIC_ADMIN_SIGNUP_BLOCKED",
  ADMIN_DELETED_COURT: "ADMIN_DELETED_COURT",
  ADMIN_RESET_USER_PASSWORD: "ADMIN_RESET_USER_PASSWORD",
  ADMIN_CHANGED_USER_STATUS: "ADMIN_CHANGED_USER_STATUS",
  ADMIN_VIEWED_ACTIVITY_LOGS: "ADMIN_VIEWED_ACTIVITY_LOGS",
  ADMIN_VIEWED_COURT_CONTACT: "ADMIN_VIEWED_COURT_CONTACT",
  BOOKING_EXPIRED: "BOOKING_EXPIRED",
  EXPIRED_HOLD_CLEANUP_RAN: "EXPIRED_HOLD_CLEANUP_RAN",
  WEBHOOK_PAYMENT_CAPTURED: "WEBHOOK_PAYMENT_CAPTURED",
  WEBHOOK_PAYMENT_FAILED: "WEBHOOK_PAYMENT_FAILED",
  WEBHOOK_REFUND_PROCESSED: "WEBHOOK_REFUND_PROCESSED",
  OWNER_VIEWED_MONTHLY_COMMISSION: "OWNER_VIEWED_MONTHLY_COMMISSION",
  OWNER_SUBMITTED_MONTHLY_COMMISSION: "OWNER_SUBMITTED_MONTHLY_COMMISSION",
  ADMIN_VIEWED_OWNER_SETTLEMENTS: "ADMIN_VIEWED_OWNER_SETTLEMENTS",
  ADMIN_VERIFIED_OWNER_COMMISSION: "ADMIN_VERIFIED_OWNER_COMMISSION",
  ADMIN_REJECTED_OWNER_COMMISSION: "ADMIN_REJECTED_OWNER_COMMISSION",
  ADMIN_RECALCULATED_OWNER_SETTLEMENTS: "ADMIN_RECALCULATED_OWNER_SETTLEMENTS",
  ADMIN_UPDATED_COURT_UPI_DETAILS: "ADMIN_UPDATED_COURT_UPI_DETAILS",
  ADMIN_UPDATED_COURT_UPI_QR: "ADMIN_UPDATED_COURT_UPI_QR",
  ADMIN_BLOCKED_COURT_APPROVAL_MISSING_UPI: "ADMIN_BLOCKED_COURT_APPROVAL_MISSING_UPI",
  USER_VIEWED_COURT_UPI_PAYMENT_DETAILS: "USER_VIEWED_COURT_UPI_PAYMENT_DETAILS",
  OWNER_COMMISSION_MARKED_OVERDUE: "OWNER_COMMISSION_MARKED_OVERDUE",
  OWNER_GENERATED_SLOTS: "OWNER_GENERATED_SLOTS",
  OWNER_GENERATED_BULK_SLOTS: "OWNER_GENERATED_BULK_SLOTS",
  OWNER_BLOCKED_DAY: "OWNER_BLOCKED_DAY",
  OWNER_MADE_DAY_AVAILABLE: "OWNER_MADE_DAY_AVAILABLE",
  OWNER_BLOCKED_SLOTS: "OWNER_BLOCKED_SLOTS",
  OWNER_UPDATED_SLOT: "OWNER_UPDATED_SLOT",
  OWNER_DELETED_SLOT: "OWNER_DELETED_SLOT",
  OWNER_CREATED_MULTIPLE_COURTS: "OWNER_CREATED_MULTIPLE_COURTS",
  OWNER_UPDATED_COURT_UPI: "OWNER_UPDATED_COURT_UPI",
  OWNER_UPLOADED_COURT_QR: "OWNER_UPLOADED_COURT_QR",
  OWNER_UPDATED_COURT_SCHEDULE: "OWNER_UPDATED_COURT_SCHEDULE",
  ADMIN_GENERATED_DAILY_SETTLEMENT: "ADMIN_GENERATED_DAILY_SETTLEMENT",
  ADMIN_GENERATED_MONTHLY_SETTLEMENT: "ADMIN_GENERATED_MONTHLY_SETTLEMENT",
  ADMIN_MARKED_SETTLEMENT_PAID: "ADMIN_MARKED_SETTLEMENT_PAID",
  OWNER_VIEWED_SETTLEMENTS: "OWNER_VIEWED_SETTLEMENTS",
  OWNER_OPENED_PAY_TO_ADMIN_PAGE: "OWNER_OPENED_PAY_TO_ADMIN_PAGE",
  OWNER_SUBMITTED_ADMIN_SETTLEMENT_PAYMENT: "OWNER_SUBMITTED_ADMIN_SETTLEMENT_PAYMENT",
  ADMIN_VERIFIED_OWNER_SETTLEMENT_PAYMENT: "ADMIN_VERIFIED_OWNER_SETTLEMENT_PAYMENT",
  ADMIN_REJECTED_OWNER_SETTLEMENT_PAYMENT: "ADMIN_REJECTED_OWNER_SETTLEMENT_PAYMENT",
  USER_SUBMITTED_DUPLICATE_UTR_ATTEMPT: "USER_SUBMITTED_DUPLICATE_UTR_ATTEMPT",
  ADMIN_APPROVED_COURT_AND_GENERATED_SLOTS: "ADMIN_APPROVED_COURT_AND_GENERATED_SLOTS"
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export interface AuditLogData {
  userId?: string | null;
  action: AuditAction | string;
  entity: string;
  entityId?: string | null;
  metadata?: Record<string, any>;
  ipAddress?: string | null;
  userAgent?: string | null;
  req?: Request;
}

const blockedMetadataKeys = new Set(["password", "newPassword", "token", "jwt", "authorization", "razorpayKeySecret", "keySecret"]);

function sanitizeMetadata(value: any): any {
  if (!value || typeof value !== "object") return value;
  if (Array.isArray(value)) return value.map(sanitizeMetadata);

  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => !blockedMetadataKeys.has(key))
      .map(([key, item]) => [key, sanitizeMetadata(item)])
  );
}

export async function createAuditLog(data: AuditLogData) {
  try {
    await prisma.auditLog.create({
      data: {
        userId: data.userId || undefined,
        action: data.action,
        entity: data.entity,
        entityId: data.entityId || undefined,
        metadata: data.metadata ? JSON.parse(JSON.stringify(sanitizeMetadata(data.metadata))) : undefined,
        ipAddress: data.ipAddress ?? data.req?.ip,
        userAgent: data.userAgent ?? data.req?.headers["user-agent"]
      }
    });
  } catch (error) {
    console.error("Error creating audit log:", error);
  }
}
